[package]
name = "flow"
version = "0.1.0"
authors = ["RJ Rybarczyk <rj@rybar.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2.18"
